
import JSZip from 'jszip';
import { parseWkt, parseLineWkt } from './geoUtils';

export const resolveMapImagePath = (baseUrl: string, path: string | undefined): string | null => {
  if (!path) return null;
  if (path.startsWith('http')) return path;
  
  const filename = path.split(/[/\\]/).filter(Boolean).pop();
  if (!filename) return null;
  
  return `${baseUrl}assets/images/${filename}`;
};

export const getContentBaseUrl = (baseUrl: string) => `${baseUrl}features/`;
export const getMapsBaseUrl = (baseUrl: string) => `${baseUrl}maps/`;

const stripFrontmatter = (md: string): string => md.replace(/^---\s*[\s\S]*?---\s*/, '');

const fetchMarkdown = async (baseUrl: string, id: string, folderName: string): Promise<string> => {
  const cleanId = id.toLowerCase().endsWith('.md') ? id.slice(0, -3) : id;
  const urls = [
    `${baseUrl}${cleanId}.md`,
    `${baseUrl}${cleanId}.MD`
  ];

  for (const url of urls) {
    const encodedUrl = encodeURI(url);
    try {
      const response = await fetch(encodedUrl);
      if (response.ok) {
        const rawText = await response.text();
        return stripFrontmatter(rawText);
      }
    } catch (error: any) {}
  }
  return `<!-- FETCH_ERROR --> 無法載入詳細說明。`;
};

export const fetchFeatureMarkdown = async (baseUrl: string, featureId: string): Promise<string> => {
  return fetchMarkdown(getContentBaseUrl(baseUrl), featureId, 'features');
};

export const fetchMapMarkdown = async (baseUrl: string, mapId: string): Promise<string> => {
  const content = await fetchMarkdown(getMapsBaseUrl(baseUrl), mapId, 'maps');
  if (!content || content.startsWith('<!-- FETCH_ERROR -->')) return "";
  return content.replace(/^##\s+.*(?:清單|列表|Features|POI)[\s\S]*$/mi, '').trim();
};

export const generateNotebookContext = (map: any, features: any[]) => {
  let context = `# 地圖脈絡：${map.name}\n\n`;
  context += `描述：${map.description || '無描述'}\n\n`;
  context += `## 景點清單 (${features.length} 個點位)\n\n`;
  
  features.forEach((f, i) => {
    context += `### ${i + 1}. ${f.name}\n`;
    context += `- ID: ${f.feature_id}\n`;
    context += `- 座標: ${f.geometry_wkt}\n`;
    if (f.description) context += `- 簡介: ${f.description}\n`;
    context += `\n`;
  });
  
  context += `\n--- \nGenerated by WalkGIS Protocol v2.0 Context Engine`;
  return context;
};

const hexToKmlColor = (hex: string) => {
  const cleanHex = hex.replace('#', '');
  if (cleanHex.length !== 6) return 'ffeb6325';
  const r = cleanHex.substring(0, 2);
  const g = cleanHex.substring(2, 4);
  const b = cleanHex.substring(4, 6);
  return `ff${b}${g}${r}`;
};

export const generateKml = (features: any[], featureContents?: Record<string, string>) => {
  let kml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
  kml += `<kml xmlns="http://www.opengis.net/kml/2.2">\n`;
  kml += `<Document>\n  <name>WalkGIS Export</name>\n`;

  features.forEach((f) => {
    let color = '#2563eb';
    try {
      if (f.meta_data) {
        const meta = JSON.parse(f.meta_data);
        color = meta.color || meta.stroke || color;
      }
    } catch(e) {}
    
    const kmlColor = hexToKmlColor(color);
    
    kml += `  <Style id="style_${f.feature_id}">\n`;
    kml += `    <LineStyle><color>${kmlColor}</color><width>6</width></LineStyle>\n`;
    kml += `    <PolyStyle><color>${kmlColor}66</color></PolyStyle>\n`;
    kml += `    <IconStyle><color>${kmlColor}</color><scale>1.2</scale></IconStyle>\n`;
    kml += `    <LabelStyle><color>ffffffff</color><scale>1.0</scale></LabelStyle>\n`;
    kml += `  </Style>\n`;
  });

  features.forEach(f => {
    const wkt = f.geometry_wkt as string;
    const styleUrl = `#style_${f.feature_id}`;
    const rawMd = featureContents ? featureContents[f.feature_id] : (f.description || '');
    const cleanMd = rawMd.startsWith('<!-- FETCH_ERROR -->') ? (f.description || '無詳細內容') : rawMd;
    const htmlDescription = `<b>${f.name}</b><br/><br/>${cleanMd.replace(/\n/g, '<br/>')}`;
    const description = `<![CDATA[${htmlDescription}]]>`;

    const pt = parseWkt(wkt);
    if (pt) {
      kml += `  <Placemark>\n    <name>${f.name}</name>\n    <description>${description}</description>\n    <styleUrl>${styleUrl}</styleUrl>\n    <Point><coordinates>${pt.lng},${pt.lat},0</coordinates></Point>\n  </Placemark>\n`;
    } else {
      const ln = parseLineWkt(wkt);
      if (ln) {
        const coordsStr = ln.map(coord => `${coord[1]},${coord[0]},0`).join(' ');
        kml += `  <Placemark>\n    <name>${f.name}</name>\n    <description>${description}</description>\n    <styleUrl>${styleUrl}</styleUrl>\n    <LineString><tessellate>1</tessellate><coordinates>${coordsStr}</coordinates></LineString>\n  </Placemark>\n`;
      }
    }
  });

  kml += `</Document>\n</kml>`;
  return kml;
};

const generateAtakManifest = (uid: string, name: string, files: string[]) => {
  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n<missionpackageversion>\n`;
  xml += `  <param name="uid" value="${uid}"/>\n`;
  xml += `  <param name="name" value="${name}"/>\n`;
  xml += `  <param name="onReceiveDelete" value="false"/>\n`;
  xml += `  <Contents>\n`;
  files.forEach(file => {
    xml += `    <Content ignore="false" zipEntry="${file}">\n`;
    xml += `      <Parameter name="uid" value="${uid}.${file}"/>\n`;
    xml += `    </Content>\n`;
  });
  xml += `  </Contents>\n</missionpackageversion>`;
  return xml;
};

export const exportAtakDataPackage = async (baseUrl: string, map: any, features: any[]) => {
  const zip = new JSZip();
  const mapName = map.name || 'WalkGIS_Map';
  const uid = map.map_id || `walkgis.${Date.now()}`;
  
  const featureContents: Record<string, string> = {};
  for (const feature of features) {
    try {
      const md = await fetchFeatureMarkdown(baseUrl, feature.feature_id);
      featureContents[feature.feature_id] = md;
    } catch (e) {
      featureContents[feature.feature_id] = feature.description || '無詳細內容';
    }
  }

  const kmlContent = generateKml(features, featureContents);
  zip.file("map.kml", kmlContent);
  
  const manifest = generateAtakManifest(uid, mapName, ["map.kml"]);
  zip.file("manifest.xml", manifest);

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${mapName}_ATAK.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const downloadFile = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
